### ISSUE TITLE
Apollo over socat

### ISSUE THREAD

**Issue by russokiwi** [MythicAgents/Apollo#61] opened 2022-01-04 12:54 UTC
Not sure if an issue for Mythic (C2 listener) or Apollo.. I have the following setup:

Apollo http payload configured to connect to c2server.domain.  c2server.domain terminates on a reverse nginx proxy with SSL in turn routing to C2 profile listening on a non SSL http port.  Everything works.

If I however terminate c2server.domain on a second proxy which uses socat as a forwarding mechanism (in front of / before Nginx) I won't get a callback.  Why not ? I would have thought maybe websockets are being used, but that shouldn't be the case with http profile ?  All other http services (there're about 20) routing through the same setup work fine.  

Please shed some light, thanks very much!

**Comment by djhohnstein** [comment] 2022-01-04 14:43
This is a routing issue. I'd check your SOCAT redirector and ensure you're getting HTTP data on that host. SOCAT can't terminate an HTTPS connection, so if it's forwarding SSL data to a non SSL port, it'll error. I'd configure the http profile on Mythic to listen on HTTPS instead of HTTP. It'd simplify your control flow significantly.

As this is a routing issue and not an agent issue, I'm going to close this ticket.

**Closed by djhohnstein** 2022-01-04 14:43 UTC

**Comment by russokiwi** [comment] 2022-01-05 02:07
No, definitely not a routing issue.  If I browse to https://c2server.domain, mythic registers that call / throws an alert so the client can see the server / that's not an issue.  Also socat is redirecting 20 other sites to the same nginx proxy using (443 => 443) and everything's working fine.   Apollo connection will not terminate.

**Comment by djhohnstein** [comment] 2022-01-05 16:04
So the reason I believe this is a routing issue and not an agent issue is that when you use the NGINX proxy, everything works fine. Then, a change is made to the C2 infrastructure between Apollo and Mythic's http profile, and it no longer works. The Mythic configuration stayed the same, the binary stayed the same, but the routing between them changed.

Firstly, I'd ask you to paste the C2 configuration of your http profile. You can view the config of that Docker container under the C2 Profiles tab in the old UI I believe. Redact information from that JSON blob as necessary.

Then, to debug where the problem is, I'd do the following:

1. Setup Apollo to beacon over HTTP to c2server.domain, and have the following routing:
apollo --http--> socat --http--> Mythic http Profile
2. Then test the following infrastructure change:
apollo--http-->socat--http-->http nginx redirectory --http--> Mythic http profile

If that works, then I'd introduce SSL first by changing the Mythic http profile to use SSL, and then repeat the same control flow form above, but with SSL instead of HTTP. My recommendation though is based on my current understanding of your infrastructure, which is:

apollo--SSL-->socat--SSL-->HTTPS Reverse Nginx Proxy --http--> Mythic http Profile

Is that correct?

**Comment by djhohnstein** [comment] 2022-01-05 16:16
You can also check the logs of the http container after restarting it with "debug" set to "true". Or, debug the binary in dnSpy and break on HTTP exception.
